//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitis2GoogleDocs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string googleDocSpreadSheetName {
            get {
                return ((string)(this["googleDocSpreadSheetName"]));
            }
            set {
                this["googleDocSpreadSheetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsGoogleDocSpreadSheetCreated {
            get {
                return ((bool)(this["IsGoogleDocSpreadSheetCreated"]));
            }
            set {
                this["IsGoogleDocSpreadSheetCreated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string googleUser {
            get {
                return ((string)(this["googleUser"]));
            }
            set {
                this["googleUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string googlePassword {
            get {
                return ((string)(this["googlePassword"]));
            }
            set {
                this["googlePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Spreadsheet name required")]
        public string googeSpreadsheetNameRequired {
            get {
                return ((string)(this["googeSpreadsheetNameRequired"]));
            }
            set {
                this["googeSpreadsheetNameRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string monitisApiKey {
            get {
                return ((string)(this["monitisApiKey"]));
            }
            set {
                this["monitisApiKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection externalMonitors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["externalMonitors"]));
            }
            set {
                this["externalMonitors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsLoggedOnToGoogle {
            get {
                return ((bool)(this["IsLoggedOnToGoogle"]));
            }
            set {
                this["IsLoggedOnToGoogle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection externalMonitorsToRead {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["externalMonitorsToRead"]));
            }
            set {
                this["externalMonitorsToRead"] = value;
            }
        }
    }
}
